        <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav pull-right">
            <li><a href="/">Inicio</a>
            </li>
            <li><a href="/features">Características</a>
            </li>
            <li class="active"><a href="#">Ingresar</a>
            </li>
            <li><a href="/sign-up">Registro</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    </div>
<!-- Nav Menu Section End -->

<!-- Hero Area Section -->

<section id="sign-in-area">

<div class="container">
    <div class="row">
<div class="col-md-12">
        <h1 class="title-big wow fadeIn"><i class="fa fa-sign-in"></i></h1>
        <h2 class="subtitle-big">Ingresa a tu cuenta</h2>
</div>


<div class="col-md-12 text-center">

<form role="form" class="sign-in-form">
  <div class="form-group col-md-offset-4 col-md-4 col-md-offset-4 wow fadeInDown">
    <input type="email" class="form-control" id="signinemail" placeholder="Enter email">
  </div>
  <div class="form-group col-md-offset-4 col-md-4 col-md-offset-4 wow fadeInDown" data-wow-delay=".7s">
    <input type="password" class="form-control" id="signinpassword" placeholder="Password">

    <a class="sign-up-button btn btn-border btn-lg col-md-offset-3 col-md-6 col-md-offset-3 wow fadeInUp" data-wow-delay="1s" href="#">Entrar</a>
  </div>
</form>
</div>
</div>
</div>
</div>
</section>

<!-- Hero Area Section End-->